version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  nodejs:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/json-calendar

commands:
  npm_install:
    steps:
      - checkout
      - run: npm i --no-progress
      - persist_to_workspace:
          root: .
          paths: .

  npm_lint:
    steps:
      - attach_workspace:
          at: .
      - run: npm run lint
  npm_test:
    steps:
      - attach_workspace:
          at: .
      - run: npm t
      - codecov/upload:
          file: coverage/*.json

jobs:
  dependencies:
    executor: nodejs
    steps:
      - npm_install
  lint:
    executor: nodejs
    steps:
      - npm_lint
  test:
    executor: nodejs
    steps:
      - npm_test

workflows:
  version: 2
  default:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - lint
